### PR TITLE
fixes no os.uname defined on windows platform

### PR DESCRIPTION
**Pull request by edgera**

### CODE REVIEW

**Comment by dimitri-yatsenko** [comment]
Great.
For the future, please increment `__version__` in `__init__.py` even for bugfixes.

**Comment by eywalker** [comment]
Do we really want to increment the version number every time we accept a PR? I'm not necessarily objecting, but wondering.

**Comment by dimitri-yatsenko** [comment]
http://semver.org/  -- I would say every bugfix, every pull request warrants `__version__` increment of the last number.   New features trigger the second number to increment.

**Comment by dimitri-yatsenko** [comment]
I would say incremental deployment to PyPI after significant bugfixes and features.

**Comment by eywalker** [comment]
Sounds good to me.

**Pull request merged**
