### PR TITLE
add mechanism to check for processing progress at schema level

### PR DESCRIPTION
**Pull request by ttngu207**
Add new method `progress` for the schema object, returning the populate progress for all imported/computed tables for a given schema (also accounts for `reserved`, `error`, `ignore` jobs)

### CODE REVIEW

**Comment by guzman-raphael** [comment]
@ttngu207 Perhaps we should consider utilizing populate's [progress](https://github.com/datajoint/datajoint-python/blob/8f9e81c6a1cae5bfc2c9cd5482b2dbeab89127e8/datajoint/autopopulate.py#L317)? You should be able to call this to determine the table populate status.

**Comment by ttngu207** [comment]
@guzman-raphael , the problem with `table.progress()` is that it is not taking into account entries in the jobs table (e.g. `reserved`, `error`, `ignore`).

**Comment by guzman-raphael** [comment]
Right, just thinking how we can report progress consistently at the table level and the schema level.

**Comment by ttngu207** [comment]
Yeah, ideally we'd fix the `.progress()` at the table level to account for `reserve`, `error` and `ignore` jobs, but that would break backward compatibility.

**Comment by guzman-raphael** [comment]
We can introduce an option to return as `pandas` too but have it default to the current behavior.

**Comment by ttngu207** [comment]
You mean for the new `schema.progress()` to return a query expression instead of pandas dataframe?

**Review by dimitri-yatsenko — APPROVED** [review]

**Comment by dimitri-yatsenko** [comment]
@ttngu207 Please resolve issues

**Comment by ttngu207** [comment]
@dimitri-yatsenko , this `schema.progress()` feature is convenient but NOT essential, if it makes sense to close this PR without merging, I'm fine with that

**Comment by dimitri-yatsenko** [comment]
Per discussion with @ttngu207 , we are closing this PR. This feature is not critical.

**Pull request closed without merging**
