### PR TITLE
0.13 enable_python_native_blobs -> True (#761)

### LINKED ISSUE #761: set 0.12 'enable_python_native_blobs' check to True
the enable_python_native_blobs check was intended only for 0.12 release transition. 
it should be removed for 0.13

### PR DESCRIPTION
**Pull request by ixcat**
fix #761

details / points:
- [X] default `enable_python_native_blobs changed` to `True`
- [X] readme updated (slight question if this should be removed/moved to docs - my thinking is after #765)
- [X] unit tests adjusted where applicable (slight judgement call)
- [X] upgrading to =True upgrade on inserting to jobs, etc. per #700 not adjusted

### CODE REVIEW

**Review by dimitri-yatsenko — APPROVED** [review]

**Review by guzman-raphael — CHANGES_REQUESTED** [review]
@ixcat Thanks for the PR man.
Looks like there are a just a few minor things left before its merge-ready.

Would you:
- Resolve the merge conflict
- Update a few more places to reflect this change:
  - https://github.com/datajoint/datajoint-python/blob/e1f24c5e8a6238593e5eaedbbc0596409381497c/README.md#L71
  - https://github.com/datajoint/datajoint-python/blob/e1f24c5e8a6238593e5eaedbbc0596409381497c/tests/test_blob_migrate.py#L10
  - https://github.com/datajoint/datajoint-python/blob/e1f24c5e8a6238593e5eaedbbc0596409381497c/tests/test_fetch_same.py#L7

**Comment by ixcat** [comment]
Hi @guzman-raphael - good catches

For README.md, just removed the `(default)` parenthetical; defaults for each version discussed higher up, but we still want to describe the behavior.

On the tests, lines now removed removed. Wasn't sure about doing this when I saw it earlier, but think you're right we should just run with the expected config.

**Comment by ixcat** [comment]
good to go, imho

**Review by guzman-raphael — APPROVED** [review]

**Comment by ixcat** [comment]
hi @guzman-raphael  - merge conflicts resolved, thanks.

**Pull request merged**
