### PR TITLE
fix pyparsing.Or bug introduced by pyparsing 2.4.1

### PR DESCRIPTION
**Pull request by dimitri-yatsenko**
Fix issue #629

### CODE REVIEW

**Comment by ixcat** [comment]
@dimitri-yatsenko - you mention in #630 this is backwards compatible, correct?

**Comment by ixcat** [comment]
also, this is for master; need same for dev if not already present

**Comment by guzman-raphael** [comment]
@ixcat I believe the purpose of #632 is to push this change to `dev` as well.

**Comment by ixcat** [comment]
ah yes missed that :) think we are good here.. merging

**Pull request merged**
