### PR TITLE
Issue 648

### PR DESCRIPTION
**Pull request by ixcat**
replacement for #649 to address #648

### CODE REVIEW

**Comment by dimitri-yatsenko** [comment]
Issue #648 has been solved in #659 by switching to `pathlib` utilities from explicit string handling. I propose closing this PR.

**Comment by ixcat** [comment]
sorry - reviewing the code - perhaps I'm missing - 
how does the new code prevent leading slashes?

```    
def _make_external_filepath(self, relative_filepath):
        """resolve the complete external path based on the relative path"""
        return PurePosixPath(self.spec['location'], relative_filepath)
```

with `'location' == '/` or == '' still yields '/':

```
>>> str(pathlib.PurePosixPath('/', 'relative/sub/path'))
'/relative/sub/path'
```

or am I missing something?

**Comment by ixcat** [comment]
But yes, the refactoring in #659 would obviate this PR as a valid fix for #648; I just don't see how it fixes #648

**Comment by dimitri-yatsenko** [comment]
```python
>>> str(Path('/', '/path')) 
'/path'
```

```python
>>> str(Path('', 'path')) 
'path'
```

If the user explicitly puts any invalid characters in the `location` path or in the filepaths, then of course, this will cause an error.

**Comment by ixcat** [comment]
ok - but this has nothing to do with #648, which is talking about the fact that '/' is valid for AWS but not minio, and wanting to (or not) be consistent about what '/' as a 'location' means between the two? or, are you saying, we don't consider this within our scope?

**Comment by ixcat** [comment]
The idea here was to force-remove '/' from both, since it doesn't work in minio, and yields 'odd'  navigation in s3, so allowing it (whether the backing supports it or not) provides little 'benefit' for users, and removing it makes it work for all cases

**Comment by ixcat** [comment]
location `'/'` is more 'meaningful' than location `''`, or maybe that's my baggage. 

treating as outside scope would also make this irrelevant. probably should document though.

**Comment by dimitri-yatsenko** [comment]
I thought the issue was the specifying the the store `location` to the empty string `""` would previously produce a leading slash. Now it doesn't. The fact that `minio` has different legal names that AWS is not something that DataJoint validates. We do not validate the path names. We simply pass them to the filesystem and s3 service without knowledge of it. If the user specifies and invalid name, then they will get an error, as expected.

**Comment by ixcat** [comment]
ok makes sense - will treat as outside scope & document `location=''` as the best way to store things at top level.

**Pull request closed without merging**
