### PR TITLE
Solved #146.

### PR DESCRIPTION
**Pull request by dimitri-yatsenko**
Subordinate relations are now declared as nested classes.  

See `tests/schema.py` and `tests/schema_simple.py` for examples.

(Corrected: typo)

### CODE REVIEW

**Comment by fabiansinz** [comment]
I guess you mean "now", not "not".

**Comment by dimitri-yatsenko** [comment]
@fabiansinz: Thank you, corrected.

**Comment by fabiansinz** [comment]
I like everything except the name `Sub`. Can we think of a better name?

**Comment by dimitri-yatsenko** [comment]
Renaming `Sub` into `Part`.

**Pull request merged**
