### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by kabilar**
- Update company name and links

### CODE REVIEW

**Review by guzman-raphael — APPROVED** [review]
@kabilar Thanks for catching this! LGTM but @dimitri-yatsenko may have some thoughts on use of `DataJoint Inc.`.

**Comment by guzman-raphael** [comment]
@kabilar Looks like the cert expired but we have a new one already that is published. Would you update references to the following to use the new certs?

`image: datajoint/nginx:v0.0.19` -> `image: datajoint/nginx:v0.1.1`

**Comment by kabilar** [comment]
Thanks @guzman-raphael.  That sounds good.  Also, I am not sure why the GitHub Actions tests failed.  I had pulled from the `datajoint:master` (`repository:branch`) prior to submitting the pull request.

**Comment by dimitri-yatsenko** [comment]
The name of the company is "DataJoint", not "DataJoint Inc."

**Comment by kabilar** [comment]
Modified the following:
- `Documentation and Tutorials` section:
    - Moved this section near the top of the document.
    - Added CodeBook link.
    - Replaced `catalog.datajoint.io` with `elements.datajoint.org`.
- To shorten the README, added collapsible sections.

**Review by guzman-raphael — APPROVED** [review]

**Comment by guzman-raphael** [comment]
Thanks @kabilar. :handshake: 

These updates look great!

**Review by dimitri-yatsenko — APPROVED** [review]

**Pull request merged**
