### PR TITLE
Add API docs

### PR DESCRIPTION
**Pull request by stes**
While `datajoint` is well documented with docstrings, I am not aware of any public API docs.

This PR adds API docs built with sphinx and the [read the docs](https://github.com/readthedocs/sphinx_rtd_theme) theme.

## Building

The API documentation can be built using sphinx by running

``` bash
pip install sphinx sphinx_rtd_theme 
pip install -e .
(cd docs-api/sphinx && make html)
```

Generated docs are written to `docs-api/docs/html/index.html`.
More details in [docs-api/README.md](docs-api/README.md)

## Expected output

I hosted an inofficial version of the docs already here: https://stes.io/datajoint/html/index.html
If you build with the code in this PR, the front page should look like this:

image

## Questions and proposals for integration

- [x] Are API docs wanted at all?
- [ ] If this PR is accepted, it would be nice to host it e.g. at `api.datajoint.io` -- would that be possible?
- [ ] Optionally, this PR could be integrated with the existing `docs.datajoint.io` as well, but I would need more details about the build process for these pages to adapt the PR.

Let me know what you think, or if you have any suggestions for improvement.

### CODE REVIEW

**Comment by guzman-raphael** [comment]
@stes Thanks for the PR! This has been very much requested by others and look forward to reviewing this. At the moment we are undergoing a bit of a restructuring on our public sites and domains. Will circle back on this as soon as we have a clearer picture when the updates will go into effect so that we can direct these docs to the most appropriate place. Appreciate your contribution :handshake:.

**Comment by stes** [comment]
Sounds good, and also happy to put in more work for integration / adapting the theme etc; let me know.

**Comment by zitrosolrac** [comment]
@stes Hey! Are you still up to date on this issue?

**Comment by stes** [comment]
> @stes Hey! Are you still up to date on this issue? 

Hi @zitrosolrac , yes I am -- I haven't heard back from the datajoint team yet, but am still happy to adapt the PR in case API docs are planned at some point :)

**Comment by zitrosolrac** [comment]
@stes we are looking into this problem and I wanted to reach out to see if you had any resources to share with me.

**Comment by stes** [comment]
@zitrosolrac basically what is in this PR, should work as a minimum example. In case you have special requirements/ideas on what to adapt, just let me know.

**Comment by zitrosolrac** [comment]
@stes yeah you can share with me if you would like!

**Comment by stes** [comment]
@zitrosolrac sorry, to clarify: I do not have any code beyond what you find in this PR and its description. In case I can help with anything, pls address the Qs I added in the PR description and ideally provide a code review on the proposed implementation, I can update the PR accordingly afterwards.

**Comment by guzman-raphael** [comment]
Hi @stes. Been far too long on this issue but we are finally ready to wrap up with this fix. 😅

I've been working with @zitrosolrac and we are integrating your suggestions + some extras with GH Actions for automation by the end of this week. Merging what is here so far so we can further collaborate on getting these docs up.

**Review by guzman-raphael — APPROVED** [review]

**Pull request merged**
