### PR TITLE
bugfix in `unite_master_parts` - handles dj.Lookup tables

### PR DESCRIPTION
**Pull request by ttngu207**

### CODE REVIEW

**Comment by dimitri-yatsenko** [comment]
Looks great. Just update CHANGELOG.mg,  docs-parts/intro/Releases_lang1.rst, and reference the bug from this PR. I will merge then.

**Comment by ttngu207** [comment]
@dimitri-yatsenko there isn't an issue filed for this bug, I just ran into it and issued a PR to fix. Should I file a new issue?

**Comment by dimitri-yatsenko** [comment]
no need for an issue. But do add a note in the CHANGELOG describing what was fixed.

**Comment by dimitri-yatsenko** [comment]
I suggest a higher-level description in CHANGELOG:
> Bugfix in listing part tables of lookup tables.

**Review by dimitri-yatsenko — APPROVED** [review]

**Comment by dimitri-yatsenko** [comment]
Does this solve #927?

**Comment by ttngu207** [comment]
@dimitri-yatsenko, I don't believe so, it is likely a different underlying cause for #927, perhaps related to diagram not stepping into the part tables and search for ancestors of each of the part, recursively.
I could be off here, haven't dig deep into 927

**Pull request merged**
